config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :users

  root "links#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
    validates :url, :priority,  presence: true
    validates :url, length: { minimum: 5 }

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :create_new_link

  private

  def create_new_link
    @link = Link.new
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.new(set_params)

#    respond_to do |format|
      if @link.save
        redirect_to links_path
#      format.json { render :index, status: :created, location: @link }
      else
       render :new
      end
#    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url, :priority, :description, :image, :comment)
    end

  def set_params()
    prm = link_params
    object = get_content(prm[:url])
    prm[:title] = object.title
    prm[:description] = object.description
    prm[:comment] = ""
    prm[:priority] = convert_priority(params[:priority])
    prm[:image] = object.favicon
    prm
  end
  
  def convert_priority(priority)
    case priority
      when "for now"
        return 1
      when "for later"
        return 2
      else
        return 3
    end
  end
  
  def get_content(url)
    LinkThumbnailer.generate(url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/_navbar.html.erb
<header class="header">
  <div class="logo">
  
  </div>
  <nav class="navbar">
    <%= form_for(@link, html: {class: 'add-url'}) do |f| %>
      <%= f.text_field :url, placeholder: 'Paste your link here', class: 'input' %>
      <div class="buttons">
        <span class = "button"> Add link:</span>
        <%= f.submit "for now",  class: 'button high', name: 'priority', value: 'for now' %>
        <%= f.submit "for later", class: 'button med', name: 'priority', value: 'for later' %>
        <%= f.submit "for later-er", class: 'button low', name: 'priority', value: 'for later-er' %>
      </div>
    <% end %>
    
  </nav>
  <% if user_signed_in? %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'button sign-out' %>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path, class: 'button sign-out' %>
  <% end %>
</header>

app/views/layouts/_sidebar.html.erb
  <aside class="sidebar">
  <form>
    <input type="text" placeholder="Search" class="search">
    <input type="submit" value="Go" class="button go">
  </form>
   <div class="show">
     <span class="title">My Links<span>
     <ul>     
     <li><a href="#"> Links for Now</a></li>
     <li><a href="#"> Links for Later</a></li>
     <li><a href="#"> Links for Later-er</a></li>
     </ul>
    </div>
    
   <div class="show">
     <span class="title">My Sessions</span> <span class="add-btn"><button>Add New</button> </span>
     <ul>     
     <li><a href="#"> Work</a></li>
     <li><a href="#"> Study</a></li>
     <li><a href="#"> Play</a></li>
     <li><a href="#"> Read</a></li>
     <li><a href="#"> Chill</a></li>
     </ul>
    </div>
  </aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linko</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=B612+Mono:400,700&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= render "layouts/navbar" %>
   
    <div class="container">
      <%= render "layouts/sidebar" %>
        <main class="main">
        <%= yield %>
        </main>
    </div>
    
  </body>
</html>

app/views/links/_cards.html.erb
  <%= link_to (link.url) do %>
    <div class="card">
  
    <img src="<%= link.image %>" class="card-img" >

  <h3 class="card-title"> <%= link.title %> </h3>
  <p class="card-text"> <%= link.description[0...150] %>...</p>
  <p class="card-actions">icons</p>
</div>
  <% end %>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
 <% @links.each do |link| %>
  
<%= render(partial: 'cards', locals: {link: link})   %>

<% end %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @link.priority %>
</p>

<p>
  <strong>Description:</strong>
  <%= @link.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @link.image %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @link.comment %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>